[project]
name = "sba-928-zacharias-braetyllo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Zacharias Braetyllo", email = "zbraetyllo@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.15.0",
    "sentencepiece>=0.2.2",
    "torch>=2.14.1",
    "transformers>=5.18.0",
]

[project.scripts]
sba-928-zacharias-braetyllo = "sba_928_zacharias_braetyllo:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
